---
- name: "SETUP | Deploying workspace configuration"
  hosts: localhost
  vars:
    dotfiles_users:
      - "{{ ansible_user_id }}"
      - "root"
    ohmyzsh_users:
      - "{{ ansible_user_id }}"
      - "root"
    ohmyzsh_themes_repos:
      - https://github.com/romkatv/powerlevel10k
  roles:
    - dotfiles
    - ohmyzsh
...
